// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL3oYFo41-VeELWwdnKB-Nmn0vbFzxPBY',
    appId: '1:931553885480:web:614e79d208b0b345bee41d',
    messagingSenderId: '931553885480',
    projectId: 'hakawati-ai',
    authDomain: 'hakawati-ai.firebaseapp.com',
    storageBucket: 'hakawati-ai.appspot.com',
    measurementId: 'G-JE49S5NJR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMLeRHVP5-QXRbz19c-yua92q-qvYvWx4',
    appId: '1:931553885480:android:7892ee063150ce3dbee41d',
    messagingSenderId: '931553885480',
    projectId: 'hakawati-ai',
    storageBucket: 'hakawati-ai.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2cvVpEZUlYogNdsJuWl2BqeSv6ZvSP3M',
    appId: '1:931553885480:ios:17d5dbbf1555cd9cbee41d',
    messagingSenderId: '931553885480',
    projectId: 'hakawati-ai',
    storageBucket: 'hakawati-ai.appspot.com',
    androidClientId: '931553885480-g17o0lur0kmbluep2jb55c6q8ajvrqu7.apps.googleusercontent.com',
    iosClientId: '931553885480-jj2nprkepr2p396rith691tnbr225jve.apps.googleusercontent.com',
    iosBundleId: 'com.ai.hakawati',
  );
}
